### ISSUE TITLE
compile error : solved

### ISSUE THREAD

**Issue by tissatussa** [Mauritz8/Vividmind#127]
i managed to compile your v1.1.0 source on Linux (Xubuntu 22.04) and the binary runs fine in CuteChess (GUI).
however, i had an error at the end of the compilation process :

```
[...]
[ 94%] Building CXX object CMakeFiles/tests.dir/src/uci.cpp.o
[ 97%] Building CXX object CMakeFiles/tests.dir/src/utils.cpp.o
[100%] Linking CXX executable tests
/usr/bin/ld: cannot open output file tests: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tests.dir/build.make:353: tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/tests.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

it's about the line _"/usr/bin/ld: cannot open output file tests: Is a directory"_.
although the error occured, the binary was created !? I guess finally some tests would be done, which failed .. but i wanted to solve this error and for that i just renamed the folder `tests` into `Tests` (on Linux file & folder names are case-sensitive) and so i just changed the references to it (text find & replace), which are in the files `compile_commands.json` and `CMakeLists.txt`.

voila !

**Comment by Mauritz8** [comment]
It indeed seems to be a name collision problem with the tests executable. I have always used a separate build directory, which is why this error has never occured to me during development. I have now updated the readme to include build instructions.

**Comment by tissatussa** [comment]
> I have now updated the readme to include build instructions.

i see those now .. that's a good way to solve this problem !
